### ISSUE TITLE
Migrate Travis jobs to GitHub Actions

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#696]
For continuous integration (CI), the OpenLoco project currently uses infrastructure from both Travis CI and GitHub Actions. Unfortunately, the former appears to no longer extend open source credits.

Previously, our AppVeyor-based jobs were migrated to GitHub Actions as well, to much satisfaction. The plan is therefore to migrate the Linux jobs from Travis CI to GitHub Actions as well.

GitHub Actions only offers the latest Xcode toolchain, which no longer comes with a 32-bits compiler toolchain. As we can currently only build 32-bits applications, we may have to give up on macOS CI for the time being.

- [x] Ubuntu i686 GCC --- as of #701
- [x] Ubuntu i686 Clang --- as of #701
- [x] Fedora i686 MinGW32 --- as of #701
- [x] clang-format --- as of 3efa2099d9f5fc93cf47e057494c3401190a3983
- [ ] macOS 10.13 Clang (Xcode 9.3)
- [x] ~macOS 10.12 Clang (Xcode 9.2)~ --- dropped as of 49367cf10c21d53c3bbb8ddf9921c7b668b6ca53
